[Ftl]
PkgStoreCacheSize=4096
  [Ftl.ChainConfig]
  ChainID = 999
  Greedy = 4
  TxExecutorType = "simple"
  TxSignerType = "fake"
  BlockSigFake = true
  MaxNonceBitLength = 1024000
  [Ftl.TxPoolConfig]
  NoLocals = true
  [Ftl.PkgPoolConfig]
  NoLocals = true
  [Ftl.Genesis]
  Round = 1539256736
  PubKey = [0]
  Sig = [0]
  Difficulty = 300000000000000000